###
# Welcome to the new js2coffee 2.0, now
# rewritten to use the esprima parser.
# try it out!
###

$ ->
  postActions = $('#list_PostActions')
  currentAction = $('#list_PostActions li.active')
  if currentAction.length == 0
    postActions.find('li:first').addClass 'active'
  postActions.find('li').on 'click', (e) ->
    e.preventDefault()
    self = $(this)
    if self == currentAction
      return
    # else
    currentAction.removeClass 'active'
    self.addClass 'active'
    currentAction = self
    return
  return

# ---
# generated by js2coffee 2.1.0